---
apiVersion: v1
kind: StatefulSet
metadata:
  name: redis-sentinel-proxy
spec:
  serviceName: redis-sentinel-proxy
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: kubernetes.io/hostname
  containers:
    - name: redis-sentinel-proxy
      image: flaccid/redis-sentinel-proxy
      env:
        - name: LISTEN_ADDRESS
          value: :6379
        - name: SENTINEL_ADDRESS
          value: redis-sentinel.default:26379
        - name: REDIS_MASTER_NAME
          value: mymaster
