---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-proxy
  labels:
    app: redis-sentinel-proxy
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      name: redis-sentinel-proxy
  selector:
    app: redis-sentinel-proxy

