---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy
    spec:
      containers:
        - name: redis-sentinel-proxy
          image: flaccid/redis-sentinel-proxy
          ports:
            - containerPort: 6379
          env:
            - name: LISTEN_ADDRESS
              value: :6379
            - name: SENTINEL_ADDRESS
              value: redis-sentinel.default:26379
            - name: REDIS_MASTER_NAME
              value: mymaster
